export const FETCH_CONTRACTORS = 'FETCH_CONTRACTORS';
export const FETCH_CONTRACTORS_SUCCESS = 'FETCH_CONTRACTORS_SUCCESS';
export const FETCH_CONTRACTORS_FAILURE = 'FETCH_CONTRACTORS_FAILURE';

export const CLOSE_MODAL_CONTRACTOR = 'CLOSE_MODAL_CONTRACTOR';
export const OPEN_MODAL_CONTRACTOR = 'OPEN_MODAL_CONTRACTOR';

export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';

export const UPDATE_QUERY = 'UPDATE_QUERY';

export const SEARCH_FOR_USERS = 'SEARCH_FOR_USERS';
export const SEARCH_FOR_COURSES = 'SEARCH_FOR_COURSES';
export const SEARCH_FOR_TOPICS = 'SEARCH_FOR_TOPICS';
export const SEARCH_FOR_ORGS = 'SEARCH_FOR_ORGS';
export const SEARCH_FOR_C_NAME = 'SEARCH_FOR_C_NAME';
export const SEARCH_FOR_DEPTH = 'SEARCH_FOR_DEPTH';

export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const SET_VIDEO_TIME = 'SET_VIDEO_TIME';
export const SET_VIDEO = 'SET_VIDEO';
export const SET_WORDS = 'SET_WORDS';

export const JOINING = 'JOINING';
export const DISCONNECTED = 'DISCONNECTED';
export const JOINED = 'JOINED';
