export const FETCH_CONTRACTORS = 'FETCH_CONTRACTORS';
export const FETCH_CONTRACTORS_SUCCESS = 'FETCH_CONTRACTORS_SUCCESS';
export const FETCH_CONTRACTORS_FAILURE = 'FETCH_CONTRACTORS_FAILURE';

export const CLOSE_MODAL_CONTRACTOR = 'CLOSE_MODAL_CONTRACTOR';
export const OPEN_MODAL_CONTRACTOR = 'OPEN_MODAL_CONTRACTOR';